server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/shop
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: Geoug6RDSnkKgZ9xxw2AOkPKcUdCpuXv
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: Geoug6RDSnkKgZ9xxw2AOkPKcUdCpuXv
