server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.65:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/shop
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: tuhhRaS7anUrZ2gKhvRBrl3nCjaN9cks
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: tuhhRaS7anUrZ2gKhvRBrl3nCjaN9cks

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
