scrape_configs:
  - job_name: shop_admin_service
    static_configs:
      - targets: ["http://192.168.0.65:8085"]
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics-client
      client_secret: XMaY9pIdJ9fL0q0xpjQ4kLCDT5dFH1bH
      token_url: http://192.168.0.65:8082/realms/shop/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: shop_catalogue_service
    static_configs:
      - targets: ["http://192.168.0.65:8081"]
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics-client
      client_secret: XMaY9pIdJ9fL0q0xpjQ4kLCDT5dFH1bH
      token_url: http://192.168.0.65:8082/realms/shop/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: