server:
  port: 8080

address:
  home: 192.168.0.135
  work: 10.10.50.201

shop:
  services:
    catalogue:
      url: lb://catalogue-service
      registrationId: keycloak
spring:
  application:
    name: manager-app-service
  boot:
    admin:
      client:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${address.work}:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://${address.work}:8082/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: JwByKV4Y8m95GDYTNqJH6jfaj5dXpv8F
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app
            client-secret: JwByKV4Y8m95GDYTNqJH6jfaj5dXpv8F
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: manager-app
            client-secret: JwByKV4Y8m95GDYTNqJH6jfaj5dXpv8F
            authorization-grant-type: client_credentials
            scope:
              - discovery

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${address.work}:8761/eureka/
