shop:
  services:
    feedback:
      url: http://localhost:8083
    catalogue:
      url: http://localhost:8081

spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: customer-app
          service-host-type: ip
        url: http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/shop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: LzljkUkRFtoGYJSGlsHFRoFEzfSG9mYs
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-service
            client-secret: S0vpvCyvgwtSOpm4lThztMKQVltnaf3f
            authorization-grant-type: client_credentials
            scope:
              - metrics_server

server:
  port: 8084

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'